# Generated by Django 6.0 on 2025-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.IntegerField(),
        ),
    ]
