# Generated by Django 6.0 on 2025-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
