# Generated by Django 6.0 on 2025-12-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material_low_stock_alert_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='low_stock_alert_sent',
        ),
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.IntegerField(help_text='Low stock limit'),
        ),
    ]
